[platformio]
default_envs = rfclown_alt

[env:rfclown_alt]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    U8g2@2.35.19
    Adafruit NeoPixel@1.12.5
    nRF24/RF24@^1.4.3
build_flags =
    -DAPP_VERSION=\"0.6.32-jam\"
    -DLAB_TX_ENABLED=0
    -DWIFI_DEAUTH_ENABLE=1
    -DJAM_ENABLE=1
